#!/usr/bin/env python

import mechanize
import sys
import socket
import fcntl
import struct

# get IP of interface
def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

# instantiate mechanize browser
br = mechanize.Browser()
try:
	br.open("https://internet.iitb.ac.in/index.php")
except Exception, e:
	br.close()
	sys.exit("Error opening url | "+str(e))


# Exit if not Authenticated
if(br.geturl() == "https://internet.iitb.ac.in/index.php"):
	br.close()
	sys.exit("Not authenticated")

# Generate IP List this PC needs to logout from
ip_list=[]
try:
	ethernet_ip = get_ip_address('eth0')
	ip_list.append(ethernet_ip)
except Exception,e:
	print "No Ethernet IP :"+ str(e)

try:
	wlan_ip = get_ip_address('wlan0')
	ip_list.append(wlan_ip)
except Exception,e:
	print "No Wifi IP :"+ str(e)


# Logout from those IPs
for ip in ip_list:
	if(br.geturl() == "https://internet.iitb.ac.in/logout.php"):
		try:
			# ip = get_ip_address('eth0')
			br.select_form(name="auth")
			br.form["ip"] = [ip] 
			# print br.form
			response = br.submit()  # submit current form
			print ip + " -> Logout"
		except Exception,e:
			print "Error logging out | "+str(e)



